name = "pixmicat-cf"
main = "src/index.ts"
compatibility_date = "2026-05-06"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "pixmicat-db"
database_id = "00000000-0000-0000-0000-000000000000"

[[kv_namespaces]]
binding = "KV"
id = "00000000000000000000000000000000"

[[r2_buckets]]
binding = "R2"
bucket_name = "pixmicat-assets"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true

[vars]
TIME_ZONE = "+8"
PIXMICAT_LANGUAGE = "zh_TW"
TITLE = "Pixmicat!-PIO"
ENVIRONMENT = "local"
